-- ============================================
-- E-Commerce Web Application - Database Schema
-- MySQL
-- ============================================

CREATE DATABASE IF NOT EXISTS ecommerce_db;
USE ecommerce_db;

-- ---------------------------
-- USERS TABLE
-- Stores both Admin and normal Users (role-based access)
-- ---------------------------
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,        -- stored as a hashed password
    role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------
-- PRODUCTS TABLE
-- ---------------------------
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    category VARCHAR(100),
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- ---------------------------
-- ORDERS TABLE
-- One row per checkout/order placed by a user
-- ---------------------------
CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    status ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled') NOT NULL DEFAULT 'pending',
    shipping_address VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ---------------------------
-- ORDER_ITEMS TABLE
-- Line items belonging to an order (many-to-many: orders <-> products)
-- ---------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,   -- price at the time of order
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- ---------------------------
-- SEED DATA (sample admin user + sample products)
-- Default admin login -> email: admin@example.com | password: admin123
-- (password below is a bcrypt hash of "admin123", generated by the app)
-- ---------------------------
INSERT INTO users (name, email, password, role) VALUES
('Admin User', 'admin@example.com', 'PLACEHOLDER_WILL_BE_SET_BY_SEED_SCRIPT', 'admin');

INSERT INTO products (name, description, price, stock, category, image_url) VALUES
('Wireless Mouse', 'Ergonomic wireless mouse with USB receiver', 599.00, 50, 'Electronics', 'https://via.placeholder.com/300x300?text=Wireless+Mouse'),
('Mechanical Keyboard', 'RGB backlit mechanical keyboard', 2499.00, 30, 'Electronics', 'https://via.placeholder.com/300x300?text=Keyboard'),
('Cotton T-Shirt', '100% cotton, comfortable fit', 399.00, 100, 'Clothing', 'https://via.placeholder.com/300x300?text=T-Shirt'),
('Running Shoes', 'Lightweight running shoes for daily use', 1999.00, 40, 'Footwear', 'https://via.placeholder.com/300x300?text=Shoes'),
('Coffee Mug', 'Ceramic coffee mug, 350ml', 249.00, 80, 'Home', 'https://via.placeholder.com/300x300?text=Mug'),
('Backpack', 'Water-resistant 30L backpack', 1599.00, 25, 'Accessories', 'https://via.placeholder.com/300x300?text=Backpack');
